const pokemons = [
  {
    nome: "Charmander",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/4.gif",    tipo: "Fogo",
    hp: 45,
    ataque: 43,
    defesa: 50,
    velocidade: 50,
    descricao:
      "Um pokémon lagarto de fogo, conhecido por sua cauda flamejante.",
  },
  {
    nome: "Charmeleon",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/5.gif",    tipo: "Fogo",
    hp: 58,
    ataque: 64,
    defesa: 58,
    velocidade: 80,
    descricao:
      "Um pokémon lagarto de fogo mais evoluído, com uma cauda mais longa e chamas mais intensas.",
  },
  {
    nome: "Charizard",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/6.gif",    tipo: "Fogo/Voador",
    hp: 78,
    ataque: 84,
    defesa: 78,
    velocidade: 100,
    descricao: "Um pokémon dragão de fogo, capaz de voar e respirar fogo.",
  },
  {
    nome: "Squirtle",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/7.gif",    tipo: "Água",
    hp: 44,
    ataque: 48,
    defesa: 65,
    velocidade: 43,
    descricao:
      "Um pokémon tartaruga aquático, conhecido por sua habilidade de esguichar água.",
  },
  {
    nome: "Wartortle",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/8.gif",    tipo: "Água",
    hp: 59,
    ataque: 63,
    defesa: 80,
    velocidade: 58,
    descricao:
      "Um pokémon tartaruga aquático mais evoluído, com uma carapaça mais resistente.",
  },
  {
    nome: "Blastoise",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/9.gif",    tipo: "Água",
    hp: 79,
    ataque: 83,
    defesa: 100,
    velocidade: 78,
    descricao:
      "Um pokémon tartaruga aquático gigante, capaz de esguichar água a longas distâncias.",
  },
  {
    nome: "Caterpie",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/10.gif",
    tipo: "Inseto",
    hp: 45,
    ataque: 30,
    defesa: 35,
    velocidade: 45,
    descricao:
      "Um pokémon lagarta pequeno e rápido, conhecido por sua habilidade de se esconder em folhas.",
  },
  {
    nome: "Metapod",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/11.gif",
    tipo: "Inseto",
    hp: 50,
    ataque: 20,
    defesa: 55,
    velocidade: 30,
    descricao:
      "Um pokémon lagarta mais evoluído, com uma carapaça mais resistente e uma habilidade de se esconder em folhas.",
  },
  {
    nome: "Butterfree",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/12.gif",
    tipo: "Inseto/Voador",
    hp: 60,
    ataque: 40,
    defesa: 40,
    velocidade: 70,
    descricao:
      "Um pokémon borboleta colorida, capaz de voar e se esconder em flores.",
  },
  {
    nome: "Weedle",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/13.gif",
    tipo: "Inseto/Venenoso",
    hp: 40,
    ataque: 40,
    defesa: 40,
    velocidade: 45,
    descricao:
      "Um pokémon lagarta venenosa, conhecido por sua habilidade de se esconder em plantas.",
  },
  {
    nome: "Kakuna",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/14.gif",
    tipo: "Inseto/Venenoso",
    hp: 45,
    ataque: 25,
    defesa: 50,
    velocidade: 35,
    descricao:
      "Um pokémon lagarta mais evoluído, com uma carapaça mais resistente e uma habilidade de se esconder em plantas.",
  },
  {
    nome: "Beedrill",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/15.gif",
    tipo: "Inseto/Venenoso",
    hp: 65,
    ataque: 80,
    defesa: 40,
    velocidade: 75,
    descricao:
      "Um pokémon abelha venenosa, capaz de voar e atacar com seu ferrão.",
  },
  {
    nome: "Pidgey",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/16.gif",
    tipo: "Normal/Voador",
    hp: 45,
    ataque: 40,
    defesa: 40,
    velocidade: 56,
    descricao:
      "Um pokémon pássaro comum, conhecido por sua habilidade de voar e se esconder em árvores.",
  },
  {
    nome: "Pidgeotto",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/17.gif",
    tipo: "Normal/Voador",
    hp: 63,
    ataque: 60,
    defesa: 60,
    velocidade: 71,
    descricao:
      "Um pokémon pássaro mais evoluído, com uma plumagem mais brilhante e uma habilidade de voar mais rápida.",
  },
  {
    nome: "Pidgeot",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/18.gif",
    tipo: "Normal/Voador",
    hp: 83,
    ataque: 80,
    defesa: 80,
    velocidade: 91,
    descricao:
      "Um pokémon pássaro gigante, capaz de voar a grandes alturas e se esconder em árvores.",
  },
  {
    nome: "Rattata",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/19.gif",
    tipo: "Normal",
    hp: 45,
    ataque: 56,
    defesa: 35,
    velocidade: 72,
    descricao:
      "Um pokémon rato comum, conhecido por sua habilidade de se esconder em buracos.",
  },
  {
    nome: "Raticate",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/20.gif",
    tipo: "Normal",
    hp: 60,
    ataque: 65,
    defesa: 40,
    velocidade: 90,
    descricao:
      "Um pokémon rato mais evoluído, com uma força maior e uma habilidade de se esconder em buracos.",
  },
  {
    nome: "Spearow",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/21.gif",
    tipo: "Normal/Voador",
    hp: 45,
    ataque: 60,
    defesa: 30,
    velocidade: 70,
    descricao:
      "Um pokémon pássaro rápido, conhecido por sua habilidade de voar e se esconder em árvores.",
  },
  {
    nome: "Fearow",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/22.gif",
    tipo: "Normal/Voador",
    hp: 65,
    ataque: 90,
    defesa: 65,
    velocidade: 100,
    descricao:
      "Um pokémon pássaro gigante, capaz de voar a grandes alturas e se esconder em árvores.",
  },
  {
    nome: "Ekans",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/23.gif",
    tipo: "Venenoso",
    hp: 35,
    ataque: 60,
    defesa: 44,
    velocidade: 55,
    descricao:
      "Um pokémon cobra venenosa, conhecido por sua habilidade de se esconder em buracos.",
  },
  {
    nome: "Arbok",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/24.gif",
    tipo: "Venenoso",
    hp: 60,
    ataque: 85,
    defesa: 69,
    velocidade: 80,
    descricao:
      "Um pokémon cobra mais evoluído, com uma força maior e uma habilidade de se esconder em buracos.",
  },
  {
    nome: "Pikachu",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/25.gif",
    tipo: "Elétrico",
    hp: 35,
    ataque: 55,
    defesa: 30,
    velocidade: 90,
    descricao:
      "Um pokémon rato elétrico, conhecido por sua habilidade de armazenar eletricidade.",
  },
  {
    nome: "Raichu",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/26.gif",
    tipo: "Elétrico",
    hp: 60,
    ataque: 90,
    defesa: 55,
    velocidade: 110,
    descricao:
      "Um pokémon rato elétrico mais evoluído, com uma força maior e uma habilidade de armazenar mais eletricidade.",
  },
  {
    nome: "Sandshrew",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/27.gif",
    tipo: "Terrestre",
    hp: 50,
    ataque: 75,
    defesa: 85,
    velocidade: 40,
    descricao:
      "Um pokémon rato de areia, conhecido por sua habilidade de se esconder em buracos.",
  },
  {
    nome: "Sandslash",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/28.gif",
    tipo: "Terrestre",
    hp: 75,
    ataque: 100,
    defesa: 110,
    velocidade: 65,
    descricao:
      "Um pokémon rato de areia mais evoluído, com uma força maior e uma habilidade de se esconder em buracos profundos, protegendo-se de ataques inimigos.",
  },
  {
    nome: "Nidoran",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/29.gif",
    tipo: "Venenoso",
    hp: 60,
    ataque: 67,
    defesa: 55,
    velocidade: 65,
    descricao:
      "Um pokémon rato venenoso, conhecido por sua habilidade de se esconder em buracos e atacar com seu veneno.",
  },
  {
    nome: "Nidorina",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/30.gif",
    tipo: "Venenoso",
    hp: 70,
    ataque: 82,
    defesa: 67,
    velocidade: 75,
    descricao:
      "Um pokémon rato venenoso mais evoluído, com uma força maior e uma habilidade de se esconder em buracos profundos.",
  },
  {
    nome: "Nidoqueen",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/31.gif",
    tipo: "Venenoso/Terrestre",
    hp: 90,
    ataque: 92,
    defesa: 87,
    velocidade: 76,
    descricao:
      "Um pokémon rato venenoso mais evoluído, com uma força maior e uma habilidade de se esconder em buracos profundos, protegendo-se de ataques inimigos.",
  },
  {
    nome: "Nidoking",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/32.gif",
    tipo: "Venenoso/Terrestre",
    hp: 91,
    ataque: 102,
    defesa: 97,
    velocidade: 81,
    descricao:
      "Um pokémon rato venenoso mais evoluído, com uma força maior e uma habilidade de se esconder em buracos profundos, protegendo-se de ataques inimigos.",
  },
  {
    nome: "Clefairy",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/35.gif",
    tipo: "Fada",
    hp: 70,
    ataque: 45,
    defesa: 48,
    velocidade: 35,
    descricao:
      "Um pokémon fada, conhecido por sua habilidade de voar e curar seus aliados.",
  },
  {
    nome: "Clefable",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/36.gif",
    tipo: "Fada",
    hp: 95,
    ataque: 70,
    defesa: 73,
    velocidade: 60,
    descricao:
      "Um pokémon fada mais evoluído, com uma força maior e uma habilidade de voar mais rápida.",
  },
  {
    nome: "Vulpix",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/37.gif",
    tipo: "Fogo",
    hp: 60,
    ataque: 60,
    defesa: 40,
    velocidade: 65,
    descricao:
      "Um pokémon raposa de fogo, conhecido por sua habilidade de gerar fogo.",
  },
  {
    nome: "Ninetales",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/38.gif",
    tipo: "Fogo",
    hp: 73,
    ataque: 81,
    defesa: 75,
    velocidade: 100,
    descricao:
      "Um pokémon raposa de fogo mais evoluído, com uma força maior e uma habilidade de gerar fogo mais intensa.",
  },
  {
    nome: "Jigglypuff",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/39.gif",
    tipo: "Normal/Fada",
    hp: 90,
    ataque: 45,
    defesa: 40,
    velocidade: 20,
    descricao:
      "Um pokémon cantor, conhecido por sua habilidade de cantar e adormecer seus oponentes.",
  },
  {
    nome: "Wigglytuff",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/40.gif",
    tipo: "Normal/Fada",
    hp: 140,
    ataque: 70,
    defesa: 90,
    velocidade: 45,
    descricao:
      "Um pokémon cantor mais evoluído, com uma força maior e uma habilidade de cantar mais intensa.",
  },
  {
    nome: "Zubat",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/41.gif",
    tipo: "Venenoso/Voador",
    hp: 75,
    ataque: 80,
    defesa: 60,
    velocidade: 90,
    descricao:
      "Um pokémon morcego venenoso, conhecido por sua habilidade de voar e atacar com seu ferrão.",
  },
  {
    nome: "Golbat",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/42.gif",
    tipo: "Venenoso/Voador",
    hp: 90,
    ataque: 100,
    defesa: 80,
    velocidade: 110,
    descricao:
      "Um pokémon morcego venenoso mais evoluído, com uma força maior e uma habilidade de voar mais rápida.",
  },
  {
    nome: "Oddish",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/43.gif",
    tipo: "Planta/Venenoso",
    hp: 65,
    ataque: 65,
    defesa: 60,
    velocidade: 40,
    descricao:
      "Um pokémon planta venenoso, conhecido por sua habilidade de gerar veneno.",
  },
  {
    nome: "Gloom",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/44.gif",
    tipo: "Planta/Venenoso",
    hp: 80,
    ataque: 80,
    defesa: 70,
    velocidade: 40,
    descricao:
      "Um pokémon planta venenoso mais evoluído, com uma força maior e uma habilidade de gerar veneno mais intensa.",
  },
  {
    nome: "Vileplume",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/45.gif",
    tipo: "Planta/Venenoso",
    hp: 95,
    ataque: 100,
    defesa: 90,
    velocidade: 50,
    descricao:
      "Um pokémon planta venenoso mais evoluído, com uma força maior e uma habilidade de gerar veneno mais intensa.",
  },
  {
    nome: "Paras",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/46.gif",
    tipo: "Inseto/Planta",
    hp: 70,
    ataque: 70,
    defesa: 55,
    velocidade: 45,
    descricao:
      "Um pokémon inseto planta, conhecido por sua habilidade de se alimentar de plantas.",
  },
  {
    nome: "Parasect",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/47.gif",
    tipo: "Inseto/Planta",
    hp: 90,
    ataque: 95,
    defesa: 80,
    velocidade: 30,
    descricao:
      "Um pokémon inseto planta mais evoluído, com uma força maior e uma habilidade de se alimentar de plantas.",
  },
  {
    nome: "Venonat",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/48.gif",
    tipo: "Inseto/Venenoso",
    hp: 60,
    ataque: 55,
    defesa: 50,
    velocidade: 45,
    descricao:
      "Um pokémon inseto venenoso, conhecido por sua habilidade de voar e atacar com seu veneno.",
  },
  {
    nome: "Venomoth",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/49.gif",
    tipo: "Inseto/Venenoso",
    hp: 70,
    ataque: 65,
    defesa: 60,
    velocidade: 90,
    descricao:
      "Um pokémon inseto venenoso mais evoluído, com uma força maior e uma habilidade de voar mais rápida.",
  },
  {
    nome: "Diglett",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/50.gif",
    tipo: "Terrestre",
    hp: 45,
    ataque: 80,
    defesa: 30,
    velocidade: 95,
    descricao: "Um pokémon rato de areia, conhecido por sua habilidade de se esconder em buracos.",
  },
  {
    nome: "Dugtrio",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/51.gif",
    tipo: "Terrestre",
    hp: 75,
    ataque: 100,
    defesa: 50,
    velocidade: 120,
    descricao: "Um pokémon rato de areia mais evoluído, com uma força maior e uma habilidade de se esconder em buracos profundos.",
  },
  {
    nome: "Meowth",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/52.gif",
    tipo: "Normal",
    hp: 40,
    ataque: 45,
    defesa: 35,
    velocidade: 90,
    descricao: "Um pokémon gato, conhecido por sua habilidade de andar em duas patas e usar suas garras para atacar.",
  },
  {
    nome: "Persian",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/53.gif",
    tipo: "Normal",
    hp: 65,
    ataque: 70,
    defesa: 60,
    velocidade: 115,
    descricao: "Um pokémon gato mais evoluído, com uma força maior e uma habilidade de andar em duas patas e usar suas garras para atacar.",
  },
  {
    nome: "Psyduck",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/54.gif",
    tipo: "Água",
    hp: 50,
    ataque: 52,
    defesa: 48,
    velocidade: 55,
    descricao: "Um pokémon pato aquático, conhecido por sua habilidade de gerar água.",
  },
  {
    nome: "Golduck",
    src: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/55.gif",
    tipo: "Água",
    hp: 80,
    ataque: 82,
    defesa: 78,
    velocidade: 85,
    descricao: "Um pokémon pato aquático mais evoluído, com uma força maior e uma habilidade de gerar água mais intensa.",
  }
];
